Feat/gh 73/crowdactions
CollActionteam/collaction_backend pull request #132
Opened 2022-05-15 07:32 UTC by edreinoso

This is the original crowdactions branch used to migrate to Clean Arch. I'm reopening it again since I thought it would be less confusing to add on top of this branch. The changes are somewhat related to crowdactions, specifically the GET all and the POST (mock) crowdactions.

2022-05-15 08:44 UTC, rubenhorn requested changes, later dismissed

2022-05-15 08:44 UTC, rubenhorn commented on template.yaml
> +              Authorizer: "NONE"
I am not sure if we should create an endpoint for creating a new crowdaction without any form of access control. Maybe we can add an AWS secret which is is passed as a parameter of the request?

2022-05-17 21:27 UTC, rubenhorn commented
@Xazin commented out CMS related endpoint

2022-05-17 21:30 UTC, Xazin approved these changes

2022-05-18 07:38 UTC, Xazin approved these changes

2022-05-18 07:38 UTC, Xazin approved these changes

2022-05-18 07:40 UTC, merged